name: tattooflashbff
services:
  - name: backend
    git:
      repo: https://github.com/YOUR_USERNAME/YOUR_REPO
      branch: main
    build:
      steps:
        - name: Install dependencies
          run: yarn install --frozen-lockfile
        - name: Build TypeScript
          run: yarn build
    run:
      cmd: yarn start
      env:
        - key: NODE_ENV
          value: production
        - key: CLOUDINARY_CLOUD_NAME
          value: ${CLOUDINARY_CLOUD_NAME}
        - key: CLOUDINARY_API_KEY
          value: ${CLOUDINARY_API_KEY}
        - key: CLOUDINARY_API_SECRET
          value: ${CLOUDINARY_API_SECRET}